services:
  backend:
    build: ./backend
    ports:
      - "5000:5050"
    command: npm start
    volumes: 
      - ./backend:/src/:/app/src/
      
  frontend:
    build: ./frontend
    ports:
      - "5173:8080"
    command: npm start
    volumes: 
      - ./frontend:/src/:/app/src/
    
